"""Report rendering — executive, CERT-In, and CREST templates.

The same findings + evidence render into the audience each report serves: a short
executive summary, and structured CERT-In / CREST layouts for a formal engagement
report. Output is Markdown (portable, diffable, converts cleanly to PDF/HTML).

These are structural templates that organize real findings and their evidence
hashes; they are not a legal certification of compliance.
"""

from __future__ import annotations

from datetime import date
from pathlib import Path

from trinetra.models.finding import Finding, Severity
from trinetra.reporting.evidence import EvidenceRecord, attach_evidence

FORMATS = ("exec", "cert-in", "crest")

_SEV_ORDER = list(reversed(Severity))  # critical first


def _counts(findings: list[Finding]) -> dict[Severity, int]:
    counts = {s: 0 for s in Severity}
    for f in findings:
        counts[f.severity] += 1
    return counts


def _sorted(findings: list[Finding]) -> list[Finding]:
    return sorted(findings, key=lambda f: list(Severity).index(f.severity), reverse=True)


def _summary_table(findings: list[Finding]) -> str:
    counts = _counts(findings)
    lines = ["| Severity | Count |", "| --- | --- |"]
    lines += [f"| {s} | {counts[s]} |" for s in _SEV_ORDER]
    return "\n".join(lines)


def _finding_block(f: Finding, ev: EvidenceRecord, *, index: int) -> str:
    loc = f.location.file or f.location.route or "n/a"
    if f.location.line:
        loc = f"{loc}:{f.location.line}"
    parts = [
        f"### {index}. {f.title}",
        "",
        f"- **Severity:** {f.severity}  |  **Confidence:** {f.confidence}",
        f"- **CWE:** {f.cwe or 'n/a'}  |  **Source:** {f.source}",
        f"- **Location:** {loc}",
        f"- **Evidence SHA-256:** `{ev.sha256}`",
    ]
    if f.remediation:
        parts.append(f"- **Remediation:** {f.remediation}")
    return "\n".join(parts)


def render_report(
    findings: list[Finding],
    *,
    fmt: str = "exec",
    engagement: str = "Trinetra security assessment",
    today: date | None = None,
) -> str:
    if fmt not in FORMATS:
        raise ValueError(f"Unknown report format: {fmt}. One of {FORMATS}.")
    evidence = attach_evidence(findings)
    when = (today or date.today()).isoformat()
    ordered = _sorted(findings)

    titles = {"exec": "Executive Summary", "cert-in": "CERT-In Assessment Report",
              "crest": "CREST Assessment Report"}
    header = [
        f"# {engagement} — {titles[fmt]}",
        "",
        f"_Generated by Trinetra on {when}. Findings: {len(findings)}._",
        "",
        "## Severity summary",
        "",
        _summary_table(findings),
        "",
    ]
    if fmt == "exec":
        body = ["## Highlights", ""]
        top = [f for f in ordered if f.severity in (Severity.CRITICAL, Severity.HIGH)][:10]
        if top:
            body += [f"- **{f.severity}** — {f.title} ({f.cwe or 'n/a'})" for f in top]
        else:
            body.append("- No high or critical findings.")
    else:
        note = {
            "cert-in": "Structured per CERT-In engagement reporting conventions.",
            "crest": "Structured per CREST assessment reporting conventions.",
        }[fmt]
        body = [f"_{note}_", "", "## Findings", ""]
        for i, f in enumerate(ordered, start=1):
            body.append(_finding_block(f, evidence[f.fingerprint], index=i))
            body.append("")
    return "\n".join([*header, *body]).rstrip() + "\n"


def write_reports(
    findings: list[Finding],
    out_dir: str | Path,
    formats: list[str],
    *,
    engagement: str = "Trinetra security assessment",
) -> list[Path]:
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for fmt in formats:
        text = render_report(findings, fmt=fmt, engagement=engagement)
        path = out / f"report-{fmt}.md"
        path.write_text(text)
        written.append(path)
    return written
